<a href="https://colab.research.google.com/github/phanikasi/first-git/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [4]:
import numpy as np
a = np.arange(20)
%timeit a**2

The slowest run took 29.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 713 ns per loop


In [5]:
l = range(10)
%timeit [i**2 for i in l]

100000 loops, best of 3: 3 µs per loop


In [0]:
ndim= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [8]:
ndim.ndim

3

In [13]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
a = np.ones((2,3))
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
e = np.eye(7,4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a = np.arange(5,dtype='int')
a

array([0, 1, 2, 3, 4])

In [21]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
np.diag(a)

array([1, 2, 3, 4])

In [23]:
# uniformly distribured variable
a = np.random.rand(4)
a

array([0.81598705, 0.85973002, 0.51591736, 0.83016355])

In [24]:
# standard normal variable
a = np.random.randn(5)
a

array([-1.20528914,  0.02255183, -1.62981835, -0.05955135, -1.39486382])